
export const wishes = [
  "Wishing you joy and prosperity.",
  "May your year be filled with laughter.",
  "Here's to a bright and shining new year.",
  "Hoping you achieve all your dreams.",
  "May you find peace and happiness.",
  "Wishing you health and wellness.",
  "Cheers to new beginnings!",
  "May your heart be light and your days bright.",
  "Hoping for your success and fulfillment.",
  "Wishing you a year of amazing adventures.",
  "May love and joy surround you.",
  "Here's to making wonderful memories.",
  "Hoping your path is filled with beauty.",
  "Wishing you strength and courage.",
  "May you inspire and be inspired.",
  "Cheers to health, wealth, and happiness.",
  "May your spirit be renewed and refreshed.",
  "Hoping for a year of positive changes.",
  "Wishing you endless moments of joy.",
  "May your creativity and passion flourish.",
  "Here's to a year of growth and learning.",
  "Hoping you find many reasons to smile.",
  "Wishing you a year as wonderful as you are.",
  "May your kindness be returned tenfold.",
  "Cheers to a future full of hope.",
  "May you find clarity and purpose.",
  "Hoping for your continued success.",
  "Wishing you a year of blissful moments.",
  "May your days be filled with sunshine.",
  "Here's to a year of peace and serenity.",
  "Hoping you are surrounded by good company.",
  "Wishing you resilience in facing challenges.",
  "May your journey be exciting and rewarding.",
  "Cheers to another year of opportunities.",
  "May your home be filled with warmth.",
  "Hoping for a year of wonderful surprises.",
  "Wishing you a heart full of gratitude.",
  "May you have the courage to be you.",
  "Here's to a year of good decisions.",
  "Hoping your spirit soars.",
  "Wishing you all the best for the year ahead.",
  "May you find beauty in the small things.",
  "Cheers to your health and happiness.",
  "May you find new passions and hobbies.",
  "Hoping you have a spectacular year.",
  "Wishing you a year of fun and excitement.",
  "May you get everything you wish for.",
  "Here's to a year of making a difference.",
  "Hoping your load is light and your heart is full.",
  "Wishing you sweet moments and fond memories.",
  "May you overcome every obstacle with grace.",
  "Cheers to a year of being your best self.",
  "May you find strength in times of trouble.",
  "Hoping you travel to new and exciting places.",
  "Wishing you a year filled with wonderful people.",
  "May you continue to learn and grow.",
  "Here's to a year of answered prayers.",
  "Hoping your good deeds multiply.",
  "Wishing you a year of abundance.",
  "May you always find a reason to celebrate.",
  "Cheers to your bright and beautiful future.",
  "May your heart and home be happy.",
  "Hoping you find joy in your work.",
  "Wishing you a year of great achievements.",
  "May you always be surrounded by love.",
  "Here's to a year of trying new things.",
  "Hoping your year is safe and sound.",
  "Wishing you a wonderful journey ahead.",
  "May you find your inner strength.",
  "Cheers to a year of peace and harmony.",
  "May you be blessed with good fortune.",
  "Hoping you have a year of good health.",
  "Wishing you many happy returns.",
  "May you achieve all your personal goals.",
  "Here's to a year of kindness and compassion.",
  "Hoping you make time for yourself.",
  "Wishing you moments of pure bliss.",
  "May you have the best year of your life.",
  "Cheers to your continued inspiration.",
  "May your friendships grow stronger.",
  "Hoping for peace and love in the world.",
  "Wishing you the courage to dream big.",
  "May your days be happy and bright.",
  "Here's to a year of fantastic experiences.",
  "Hoping you find happiness in every day.",
  "Wishing you a year of perfect moments.",
  "May you shine brighter than ever before.",
  "Cheers to your happiness and well-being.",
  "May you be a beacon of hope for others.",
  "Hoping your year is filled with music and art.",
  "Wishing you a year of great stories to tell.",
  "May your spirit be adventurous.",
  "Here's to a year of living life to the fullest.",
  "Hoping for a prosperous and successful year.",
  "Wishing you a year of wonder and awe.",
  "May you be happy and see others happy.",
  "Cheers to making the world a better place."
];
