
export const wishes = [
  "Joy and laughter", "Health and happiness", "Peace and love", "Success and prosperity", 
  "New adventures", "Lasting friendships", "Unforgettable memories", "Creative inspiration",
  "Inner peace", "Strength and resilience", "Good fortune", "Clear direction", "Personal growth",
  "Happy moments", "Wonderful surprises", "Dreams coming true", "A year of fun",
  "Meaningful connections", "Positive changes", "Abundant blessings", "Courage to dare",
  "Wisdom to choose", "Patience to wait", "A kind heart", "A sharp mind", "A healthy body",
  "A happy soul", "Lots of smiles", "Warm hugs", "Sweet dreams", "Sunny days",
  "Starry nights", "Good books", "Great music", "Delicious food", "Safe travels",
  "New opportunities", "Achieved goals", "Stronger bonds", "Less stress", "More sleep",
  "Time for hobbies", "Moments of stillness", "Confidence boost", "Clarity of thought",
  "Supportive community", "Financial stability", "A helping hand", "A shoulder to lean on",
  "Hope for the future", "Gratitude for the present", "Forgiveness for the past",
  "Self-love and care", "Understanding and empathy", "Generosity and kindness",
  "A sense of purpose", "A feeling of belonging", "Unwavering optimism",
  "The courage to be you", "The freedom to explore", "The joy of learning", "A peaceful home",
  "A clean environment", "Harmony with nature", "Respect for all", "Equality and justice",
  "An end to conflict", "Healing for the world", "Brighter tomorrows", "Lasting impact",
  "Simple pleasures", "Deep conversations", "Heartfelt compliments", "Unexpected gifts",
  "Spontaneous dancing", "Singing out loud", "Comfortable silence", "A favorite movie",
  "A warm blanket", "A hot cup of tea", "A good workout", "A relaxing bath", "A fresh start",
  "A second chance", "A clean slate", "A new perspective", "A better you", "A better world",
  "Love that grows", "Friendship that lasts", "Family that supports", "Work that fulfills",
  "Play that rejuvenates", "Rest that restores", "Faith that guides", "Hope that inspires",
  "Dreams that motivate", "Passion that drives", "Purpose that grounds", "Vision that leads",
  "Happiness always", "Cheers to the new year", "To new beginnings", "Let your light shine",
  "Make it happen", "Stay positive", "Work hard", "Dream big", "Be kind", "Stay humble",
  "Be grateful", "Live fully", "Love deeply", "Laugh often", "Never give up",
  "Believe in yourself", "Trust the journey", "Embrace change", "Seek adventure",
  "Find your magic", "Create your own sunshine", "Be the reason someone smiles",
  "Do what you love", "Love what you do", "Make every moment count", "Collect memories, not things",
  "Live in the moment", "Be present", "Stay curious", "Keep learning", "Keep growing",
  "Be fearless", "Be brave", "Be bold", "Be you", "Best year ever", "Here's to us",
  "To the future", "May all your wishes come true", "Good vibes only", "Positive thoughts",
  "Happy New Year", "Spread love", "Spread kindness", "Make a difference",
  "Shine bright", "Stay strong", "You got this", "One day at a time", "Enjoy the ride",
  "Make today amazing", "Good things are coming", "The best is yet to come",
  "Seize the day", "Carpe Diem", "Hakuna Matata", "No worries", "Be happy",
  "Live your best life", "Follow your heart", "Listen to your gut", "Trust your intuition",
  "Take risks", "Make mistakes", "Learn from them", "Forgive yourself", "Move on",
  "Let go", "Breathe", "Relax", "Enjoy", "Celebrate life", "Dance in the rain",
  "Chase rainbows", "Watch sunsets", "Gaze at stars", "Smell the flowers", "Feel the breeze",
  "Listen to the birds", "Connect with nature", "Find beauty everywhere", "Appreciate the little things",
  "Count your blessings", "Practice gratitude", "Give back", "Help others", "Be a good human",
  "Leave a legacy", "Inspire others", "Lead by example", "Be the change", "Make the world better"
];
