
export const wishes = [
  "សូមឱ្យរៀនពូកែ", "Health and happiness", "Peace and love", "Success and prosperity", 
  "New adventures", "Lasting friendships", "Unforgettable memories", "Creative inspiration",
  "Inner peace", "Strength and resilience", "Good fortune", "ស៊ូៗណា! ថ្ងៃស្អែកនឹងល្អជាងនេះ", "Personal growth",
  "Happy moments", "Wonderful surprises", "Dreams coming true", "A year of fun",
  "Meaningful connections", "Positive changes", "សូមឱ្យសំណាងល្អរាល់ថ្ងៃ", "Courage to dare",
  "Wisdom to choose", "Patience to wait", "A kind heart", "A sharp mind", "A healthy body",
  "A happy soul", "Lots of smiles", "Warm hugs", "Sweet dreams", "Sunny days",
  "Starry nights", "Good books", "Great music", "Delicious food", "Safe travels",
  "ខំរៀនដើម្បីខ្លួនឯង", "Achieved goals", "Stronger bonds", "ជឿជាក់លើខ្លួនឯង អ្នកនឹងល្អប្រសើរ", "More sleep",
  "Time for hobbies", "Moments of stillness", "Confidence boost", "Clarity of thought",
  "Supportive community", "Financial stability", "A helping hand", "កុំឱ្យការឈឺចាប់បំផ្លាញក្តីសង្ឃឹមរបស់អ្នក",
  "Hope for the future", "Gratitude for the present", "Forgiveness for the past",
  "Self-love and care", "សូមឱ្យចាំមេរៀនបានល្អ", "Generosity and kindness",
  "A sense of purpose", "សូមឱ្យបញ្ចប់ការសិក្សាដោយជោគជ័យ", "សូមឱ្យរាល់ការខិតខំប្រឹងប្រែងទទួលបានផលល្អ",
  "The courage to be you", "សូមឱ្យសុខសប្បាយ", "The joy of learning", "A peaceful home",
  "A clean environment", "សូមឱ្យជៀសផុតពីជំងឺទាំងពួង", "Respect for all", "Equality and justice",
  "An end to conflict", "Healing for the world", "Brighter tomorrows", "Lasting impact",
  "Simple pleasures", "Deep conversations", "Heartfelt compliments", "Unexpected gifts",
  "Spontaneous dancing", "Singing out loud", "Comfortable silence", "បើគេមិនស្រលាញ់យើងទេ គួរតែដោះលែងគេទៅ",
  "A warm blanket", "A hot cup of tea", "សូមឱ្យការចងចាំអាក្រក់ៗរលាយបាត់ទៅ", "A relaxing bath", "A fresh start",
  "A second chance", "ត្រូវរៀនញញឹមឱ្យខ្លួនឯង ទោះគ្មានគេ", "A new perspective", "A better you", "A better world",
  "Love that grows", "ជូនពរឱ្យរកការងារបានធ្វើភ្លាមក្រោយរៀនចប់", "Family that supports", "Work that fulfills",
  "Play that rejuvenates", "Rest that restores", "Faith that guides", "Hope that inspires",
  "Dreams that motivate", "ធ្វើដំណើរទីជិតទីឆ្ងាយ សូមឱ្យមានសុវត្ថិភាព", "Purpose that grounds", "សូមឱ្យចិត្តខ្ញុំឈប់នឹកគេ",
  "Happiness always", "Cheers to the new year", "To new beginnings", "Let your light shine",
  "Make it happen", "Stay positive", "Work hard", "Dream big", "Be kind", "Stay humble",
  "ជូនពរឱ្យការការពារសារណាបានជោគជ័យ", "Live fully", "Love deeply", "លាហើយការឈឺចាប់ សួស្តីភាពរឹងមាំ", "Never give up",
  "Believe in yourself", "Trust the journey", "Embrace change", "Seek adventure",
  "Find your magic", "Create your own sunshine", "Be the reason someone smiles",
  "Do what you love", "Love what you do", "Make every moment count", "Collect memories, not things",
  "Live in the moment", "សូមឱ្យជួបតែរឿងល្អៗ", "Stay curious", "សូមឱ្យជីវិតមានតែភាពស្ងប់សុខ", "Keep growing",
  "Be fearless", "Be brave", "Be bold", "ជូនពរឆ្នាំថ្មី ហេង ហេង", "Best year ever", "Here's to us",
  "To the future", "May all your wishes come true", "សូមឱ្យថ្ងៃនេះជាថ្ងៃពិសេសរបស់យើង", "សូមឱ្យពេលវេលាជួយព្យាបាលរបួសបេះដូងមួយនេះ",
  "Happy New Year", "Spread love", "Spread kindness", "អបអរសាទរចំពោះការចាប់ផ្តើមថ្មី!",
  "Shine bright", "Stay strong", "សូមឱ្យរកស៊ីមានបាន", "One day at a time", "សូមឱ្យសម្រេចបំណងប្រាថ្នាធំៗ",
  "សូមឱ្យឡើងប្រាក់ខែ", "Good things are coming", "The best is yet to come",
  "Seize the day", "Carpe Diem", "សូមឱ្យបានប្រកបដោយពុទ្ធពរទាំង ៤ ប្រការ គឺ អាយុ វណ្ណៈ សុខៈ ពលៈ កុំបីឃ្លៀងឃ្លាតឡើយ", "No worries", "Be happy",
  "Live your best life", "Follow your heart", "សូមឱ្យឆ្នាំនេះពោរពេញដោយស្នាមញញឹម", "Trust your intuition",
  "Take risks", "Make mistakes", "Learn from them", "Forgive yourself", "Move on",
  "Let go", "Breathe", "Relax", "Enjoy", "Celebrate life", "Dance in the rain",
  "Chase rainbows", "Watch sunsets", "សូមឱ្យឆាប់ក្លាយជាសេដ្ឋី", "Smell the flowers", "Feel the breeze",
  "Listen to the birds", "Connect with nature", "Find beauty everywhere", "សូមឱ្យយប់នេះជាយប់ចុងក្រោយនៃទឹកភ្នែក",
  "Count your blessings", "Practice gratitude", "Give back", "ទឹកភ្នែកជាមិត្តល្អបំផុតនៅពេលនេះ", "សុំទោសបេះដូង ដែលធ្វើឱ្យឯងឈឺ",
  "Leave a legacy", "សូមឱ្យលុយចូលដូចទឹក", "សូមឱ្យចៅហ្វាយស្រលាញ់ និងពេញចិត្ត", "Be the change", "Make the world better"
];
